CREATE TABLE Person (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
age VARCHAR(50) NOT NULL,
has_license VARCHAR(3) NOT NULL);

CREATE TABLE Car(
id INT PRIMARY KEY AUTO_INCREMENT,
brand VARCHAR (50) NOT NULL,
model VARCHAR (50) NOT NULL,
price VARCHAR(50) NOT NULL));




CREATE TABLE PersonCar (
person_id INT,
car_id INT,
PRIMARY KEY(person_id, car_id),
FOREIGN KEY (person_id) REFERENCES
Person(id) ON DELETE CASCADE,
FOREIGN KEY (car_id) REFERENCES Car(id)
ON DELETE CASCADE);